title: Hui Sheng's Homepage
page-top-title: Hui Sheng
top-section-bg-text: Tianjin Academy of Agricultural Sciences
home-subtitle: Hui Sheng&ensp;|&ensp;盛辉
copyright-text: '&copy; Hui Sheng 2018-2025. All Rights Reserved.'
